
"""
Python dictionaries are used for mapping. Here is the schema:

"ZOOM_KEY": ("SB NORM VALUE", NORM MASTER VALUES ID)

"""

position_function_mappings = {
    "Accounting": ("Accounting/Finance", 2),
    "Advertising": ("Marketing", 6),
    "Banking": ("Accounting/Finance", 2),
    "Benefits & Compensation": ("HR", 3),
    "Biometrics": ("Engineering", 28),
    "Biotechnical Engineering": ("Engineering", 28),
    "Branding": ("Marketing", 6),
    "Business Development": ("Sales", 4),
    "Change Management": ("Consultant", 29),
    "Chemical Engineering": ("Engineering", 28),
    "Civil Engineering": ("Engineering", 28),
    "Communications": ("Marketing", 6),
    "Compliance": ("Operations", 30),
    "Contracts": ("Operations", 30),
    "Customer Relations": ("Customer Service", 7),
    "Database Eng & Design": ("IT", 8),
    "Dentists": ("Health Care Provider", 88),
    "Diversity": ("Operations", 30),
    "Doctors": ("Health Care Provider", 88),
    "Doctors - General Practice": ("Health Care Provider", 88),
    "Doctors - Specialist Practice": ("Health Care Provider", 88),
    "Engineering": ("Engineering", 28),
    "Facilities": ("Operations", 30),
    "Finance": ("Accounting/Finance", 2),
    "General Marketing": ("Marketing", 6),
    "Gov Lawyers & Legal Prof": ("Legal", 9),
    "Governmental Lawyers & Legal Professionals": ("Legal", 9),
    "Hardware Engineering": ("Engineering", 28),
    "Health Professionals": ("Health Care Provider", 88),
    "HR Generalist": ("HR", 3),
    "Human Resources Generalist": ("HR", 3),
    "Industrial Engineering": ("Engineering", 28),
    "Information Technology": ("IT", 8),
    "Investment Banking": ("Accounting/Finance", 2),
    "Lawyers & Legal Prof": ("Legal", 9),
    "Lawyers & Legal Professionals": ("Legal", 9),
    "Logistics": ("Operations", 30),
    "Medical Affairs": ("Health Care Provider", 88),
    "Medical Devices": ("Engineering", 28),
    "Nurses": ("Health Care Provider", 88),
    "Operations": ("Operations", 30),
    "Product Management": ("Marketing", 6),
    "Quality Assurance": ("Engineering", 28),
    "Quality Management": ("Operations", 30),
    "Recruiting": ("HR", 3),
    "Sales": ("Sales", 4),
    "Software Engineering": ("IT", 8),
    "Sourcing": ("Operations", 30),
    "Technical": ("Engineering", 28),
    "Wealth Management": ("Accounting/Finance", 2),
    "Web Development": ("IT", 8),
    "Analyst": ("Operations", 30),
    "Architect": ("Engineering", 28),
    "Board Member": ("Executive Management", 1),
    "Database Engineering & Design": ("IT", 8),
    "Education": ("Teacher", 94),
    "Educator": ("Teacher", 94),
    "Executive Assistant": ("Staff", 10),
    "Function": ("Staff", 10),
    "General Executive": ("Executive Management", 1),
    "Program Management": ("Operations", 30),
    "Project Management": ("Operations", 30),
}

position_level_mappings = {
    "Board Members": ("Other C-level", 34),
    "C-level": ("Other C-level", 34),
    "C-Level": ("Other C-level", 34),
    "VP-level": ("VP/EVP/SVP", 35),
    "Director": ("Director", 36),
    "Manager": ("Manager", 37),
    "Non-Manager": ("Staff", 39),
    "NonManagement": ("Staff", 39),
    "Vice President": ("VP/EVP/SVP", 35),
}

company_type_mappings = {
    "Accounting & Accounting Services": ("Financial Services", 54),
    "Advertising & Marketing": ("Advertising", 40),
    "Aerospace & Defense": ("Aerospace and Aviation", 41),
    "Aggregates, Concrete & Cement": ("Construction", 49),
    "Agriculture": ("Agricultural/Forestry/Fishing", 42),
    "Airlines Airports & Air Services": ("Aerospace and Aviation", 41),
    "Amusement Parks, Arcades & Attractions": ("Amusement and Entertainment", 43),
    "Animals & Livestock": ("Agricultural/Forestry/Fishing", 42),
    "Apparel & Accessories": ("Apparel and Accessories", 44),
    "Apparel & Accessories Retail": ("Apparel and Accessories", 44),
    "Appliances": ("Manufacturing", 64),
    "Architecture, Engineering & Design": ("Consulting", 50),
    "Auctions": ("Retail", 72),
    "Automobile Dealers": ("Automotive", 45),
    "Automobile Parts Stores": ("Automotive", 45),
    "Automobiles": ("Automotive", 45),
    "Automotive Service & Collision Repair": ("Automotive", 45),
    "Banking": ("Finance", 53),
    "Batteries, Power Storage Equipment & Generators": ("Industrial Supplies/Equipment", 59),
    "Biotechnology": ("Biotechnology", 112),
    "Boats & Submarines": ("Manufacturing", 64),
    "Broadcasting": ("Media", 66),
    "Brokerage": ("Financial Services", 54),
    "Building Materials": ("Construction", 49),
    "Business Intelligence (BI) Software": ("IT", 61),
    "Business Intelligence Software(BI)": ("IT", 61),
    "Business Services": ("Professional Services", 69),
    "Cable & Satellite": ("Telecommunications", 74),
    "Call Centers & Business Centers": ("Professional Services", 69),
    "Car & Truck Rental": ("Automotive", 45),
    "Chambers of Commerce": ("Non-Profit/Association", 67),
    "Charitable Organizations & Foundations": ("Non-Profit/Association", 67),
    "Chemicals": ("Chemicals", 46),
    "Chemicals & Related Products": ("Chemicals", 46),
    "Chemicals, Petrochemicals, Glass & Gases": ("Chemicals", 46),
    "Cities, Towns & Municipalities": ("Government", 56),
    "Cleaning Products": ("Manufacturing", 64),
    "Colleges & Universities": ("Higher Education", 101),
    "Commercial & Residential Construction": ("Construction", 49),
    "Commercial Printing": ("Professional Services", 69),
    "Computer Equipment & Peripherals": ("Computer and Electronics", 48),
    "Computer Networking Equipment": ("Computer and Electronics", 48),
    "Computer Storage Equipment": ("Industrial Supplies/Equipment", 59),
    "Construction": ("Construction", 49),
    "Consumer Electronics": ("Computer and Electronics", 48),
    "Consumer Electronics & Computers": ("Computer and Electronics", 48),
    "Consumer Electronics & Computers Retail": ("Computer and Electronics", 48),
    "Consumer Goods": ("Manufacturing", 64),
    "Consumer Services": ("Consulting", 50),
    "Content & Collaboration Software": ("IT", 61),
    "Convenience Stores, Gas Stations & Liquor Stores": ("Retail", 72),
    "Cosmetics Beauty Supply & Personal Care Products": ("Manufacturing", 64),
    "Credit Cards & Transaction Processing": ("Financial Services", 54),
    "Crops": ("Agricultural/Forestry/Fishing", 42),
    "Cultural": ("Non-Profit/Association", 67),
    "Custom Software & Technical Consulting": ("Consulting", 50),
    "Customer Relationship Management (CRM) Software": ("IT", 61),
    "Customer Relationship Management Software": ("IT", 61),
    "Database & File Management Software": ("IT", 61),
    "Debt Collection": ("Financial Services", 54),
    "Department Stores & Superstores": ("Retail", 72),
    "Department Stores, Shopping Centers & Superstores": ("Retail", 72),
    "Drug Manufacturing & Research": ("Pharmaceuticals", 120),
    "Drug Stores & Pharmacies": ("Retail", 72),
    "Education": ("Education", 51),
    "Electricity Oil & Gas": ("Energy", 52),
    "Electricity, Oil & Gas": ("Energy", 52),
    "Electronic Components": ("Computer and Electronics", 48),
    "Electronics": ("Computer and Electronics", 48),
    "Emergency Medical Transportation & Services": ("General Health Care", 115),
    "Energy, Utilities & Waste Treatment": ("Energy", 52),
    "Engineering Software": ("IT", 61),
    "Enterprise Resource Planning (ERP) Software": ("IT", 61),
    "Enterprise Resource Planning Software(ERP)": ("IT", 61),
    "Facilities Management & Commercial Cleaning": ("Professional Services", 69),
    "Film/Video Production & Services": ("Media", 66),
    "Finance": ("Finance", 53),
    "Financial, Legal & HR Software": ("IT", 61),
    "Fitness & Dance Facilities": ("Amusement and Entertainment", 43),
    "Flowers, Gifts & Specialty": ("Retail", 72),
    "Flowers, Gifts & Specialty Stores": ("Retail", 72),
    "Food & Beverages": ("Food/Beverages", 55),
    "Food Service": ("Food/Beverages", 55),
    "Food, Beverages & Tobacco": ("Food/Beverages", 55),
    "Freight & Logistics Services": ("Transportation/Warehouse/Logistics", 73),
    "Funeral Homes & Funeral Related Services": ("Professional Services", 69),
    "Furniture": ("Manufacturing", 64),
    "Gambling & Gaming": ("Amusement and Entertainment", 43),
    "Gas Stations, Convenience & Liquor Stores": ("Retail", 72),
    "Gases": ("Chemicals", 46),
    "Glass & Clay": ("Manufacturing", 64),
    "Government": ("Government", 56),
    "Grocery": ("Retail", 72),
    "Grocery Retail": ("Retail", 72),
    "Hair Salons": ("Professional Services", 69),
    "Health & Nutrition Products": ("Food/Beverages", 55),
    "Healthcare": ("Healthcare", 57),
    "Healthcare Software": ("IT", 61),
    "Home Improvement & Hardware": ("Retail", 72),
    "Home Improvement & Hardware Retail": ("Real Estate/Leasing", 71),
    "Hospitality": ("Hospitality/Travel", 58),
    "Hospitals & Clinics": ("Hospital", 116),
    "Household Goods": ("Manufacturing", 64),
    "Human Resources & Staffing": ("Professional Services", 69),
    "Industrial Machinery & Equipment": ("Industrial Supplies/Equipment", 59),
    "Information & Document Management": ("IT", 61),
    "Information Collection & Delivery": ("IT", 61),
    "Insurance": ("Insurance", 60),
    "Internet Service Providers, Web Host, etc": ("Telecommunications", 74),
    "Internet Service Providers, Website Hosting & Internet-related Services": ("Telecommunications", 74),
    "Investment Banking": ("Finance", 53),
    "Jewelry & Watch Retail": ("Retail", 72),
    "Jewelry & Watches": ("Retail", 72),
    "K-12 Schools": ("Education", 51),
    "Laundry & Dry Cleaning Services": ("Professional Services", 69),
    "Law Firms & Legal Services": ("Law Firm", 62),
    "Libraries": ("Education", 51),
    "Lodging & Resorts": ("Lodging", 63),
    "Lumber & Wood Production": ("Agricultural/Forestry/Fishing", 42),
    "Lumber, Wood Production & Timber Operations": ("Agricultural/Forestry/Fishing", 42),
    "Management Consulting": ("Consulting", 50),
    "Manufacturing": ("Manufacturing", 64),
    "Marine Shipping & Transportation": ("Transportation/Warehouse/Logistics", 73),
    "Media & Internet": ("Media", 66),
    "Medical Devices & Equipment": ("Medical Devices & Equipment", 118),
    "Medical Testing & Clinical Laboratories": ("Medical Testing & Clinical Laboratories", 119),
    "Membership Organizations": ("Non-Profit/Association", 67),
    "Metals & Minerals": ("Manufacturing", 64),
    "Metals & Mining": ("Manufacturing", 64),
    "Mining": ("Manufacturing", 64),
    "Miscellaneous Building Material Flooring Cabinets": ("Construction", 49),
    "Miscellaneous Building Materials (Flooring, Cabinets etc.)": ("Construction", 49),
    "Motor Vehicle Dealers": ("Automotive", 45),
    "Motor Vehicle Parts": ("Automotive", 45),
    "Motor Vehicles": ("Automotive", 45),
    "Movie Theaters": ("Amusement and Entertainment", 43),
    "Multimedia & Graphic Design": ("Media", 66),
    "Multimedia, Games and graphics Software": ("IT", 61),
    "Museums & Art Galleries": ("Non-Profit/Association", 67),
    "Music & Music Related Services": ("Media", 66),
    "Music & Performing Arts": ("Amusement and Entertainment", 43),
    "Network Security Hardware & Software": ("Computer and Electronics", 48),
    "Networking Software": ("IT", 61),
    "Newspapers & News Services": ("Media", 66),
    "Office Products": ("Office Supplies", 68),
    "Office Products Retail & Distribution": ("Office Supplies", 68),
    "Oil & Gas Exploration & Services": ("Energy", 52),
    "Organizations": ("N/A", 93),
    "Personal Computers & Peripherals": ("Computer and Electronics", 48),
    "Pet Products": ("Manufacturing", 64),
    "Petrochemicals": ("Chemicals", 46),
    "Pharmaceuticals": ("Pharmaceuticals", 120),
    "Photographic & Optical Equipment": ("Manufacturing", 64),
    "Photography Studio": ("Retail", 72),
    "Plastic, Packaging & Containers": ("Manufacturing", 64),
    "Plumbing & HVAC Equipment": ("Industrial Supplies/Equipment", 59),
    "Power Conversion & Protection Equipment": ("Utilities", 75),
    "Public Safety": ("Government", 56),
    "Publishing": ("Publishing", 70),
    "Pulp & Paper": ("Agricultural/Forestry/Fishing", 42),
    "Radio Stations": ("Media", 66),
    "Rail, Bus & Taxi": ("Transportation/Warehouse/Logistics", 73),
    "Real Estate": ("Real Estate/Leasing", 71),
    "Record, Video & Book Stores": ("Retail", 72),
    "Records, Videos & Books": ("Retail", 72),
    "Recreation": ("Amusement and Entertainment", 43),
    "Religious Organizations": ("Non-Profit/Association", 67),
    "Rental - Video & DVD": ("Retail", 72),
    "Rental Other - Furniture, A/V & Construction & Industrial Equip.": ("Retail", 72),
    "Restaurants": ("Food/Beverages", 55),
    "Retail": ("Retail", 72),
    "Retail Software": ("IT", 61),
    "Search Engines & Internet Portals": ("IT", 61),
    "Security Products & Services": ("Professional Services", 69),
    "Security software": ("IT", 61),
    "Semiconductor & Semiconductor Equipment": ("Industrial Supplies/Equipment", 59),
    "Semiconductors": ("Manufacturing", 64),
    "Software": ("IT", 61),
    "Software & Technical Consulting": ("Consulting", 50),
    "Software Development & Design": ("IT", 61),
    "Sporting & Recreational Equipment": ("Manufacturing", 64),
    "Sporting & Recreational Equipment Retail": ("Retail", 72),
    "Sporting Goods": ("Retail", 72),
    "Sports Teams & Leagues": ("Amusement and Entertainment", 43),
    "Storage & System Management Software": ("IT", 61),
    "Supply Chain Management (SCM) Software": ("IT", 61),
    "Supply chain management Software(SCM)": ("IT", 61),
    "Telecommunication Equipment": ("Telecommunications", 74),
    "Telecommunications": ("Telecommunications", 74),
    "Telephony & Wireless": ("Telecommunications", 74),
    "Television Stations": ("Media", 66),
    "Test & Measurement Equipment": ("Industrial Supplies/Equipment", 59),
    "Textiles & Apparel": ("Apparel and Accessories", 44),
    "Tires & Rubber": ("Manufacturing", 64),
    "Tobacco": ("Food/Beverages", 55),
    "Toys & Games": ("Manufacturing", 64),
    "Training": ("Consulting", 50),
    "Translation & Linguistic Services": ("Communications/PR", 47),
    "Transportation": ("Transportation/Warehouse/Logistics", 73),
    "Travel Agencies & Services": ("Hospitality/Travel", 58),
    "Trucking, Moving & Storage": ("Transportation/Warehouse/Logistics", 73),
    "Venture Capital": ("Finance", 53),
    "Venture Capital & Private Equity": ("Finance", 53),
    "Veterinary Care": ("General Health Care", 115),
    "Vitamins, Supplements & Health Stores": ("Retail", 72),
    "Waste Treatment Environmental Svc, Recycling": ("Utilities", 75),
    "Waste Treatment, Environmental Services & Recycling": ("Utilities", 75),
    "Water & Water Treatment": ("Utilities", 75),
    "Weight & Health Management": ("General Health Care", 115),
    "Wineries & Breweries": ("Food/Beverages", 55),
    "Wire & Cable": ("Telecommunications", 74),
    "Zoos & National Parks": ("Amusement and Entertainment", 43),
    "Miscellaneous Building Materials - Flooring, Cabinets, etc.":("Construction", 49),
    "Airlines, Airports & Air Services": ("Aerospace and Aviation", 41),
    "Cosmetics, Beauty Supply & Personal Care Products": ("Manufacturing", 64),
    "Rental - Other - Furniture, A/V, Construction & Industrial Equipment": ("Industrial Supplies/Equipment", 59),
    "Customer Relationship Management Software(CRM)": ("IT", 61),
    "Rental - Video & DVD ": ("Amusement and Entertainment", 43),
}
